apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.0.1.160:8080"
  restuser: "admin"
  restuserkey: "secretpassword"
  volumetype: "replicate:2"
