apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://3.143.241.48:8080"
  restuser: "admin"
  restuserkey: "secretpassword"
  volumetype: "replicate:2"
